// <auto-generated />
using DogBreeds.Mvc.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DogBreeds.Mvc.Migrations
{
    [DbContext(typeof(DogBreedsContext))]
    [Migration("20190704134340_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DogBreeds.Mvc.Dal.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BreedId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("DogBreeds.Mvc.Dal.Models.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BreedId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.ToTable("Individuals");
                });

            modelBuilder.Entity("DogBreeds.Mvc.Dal.Models.Breed", b =>
                {
                    b.HasOne("DogBreeds.Mvc.Dal.Models.Breed", "ParentBreed")
                        .WithMany()
                        .HasForeignKey("BreedId");
                });

            modelBuilder.Entity("DogBreeds.Mvc.Dal.Models.Individual", b =>
                {
                    b.HasOne("DogBreeds.Mvc.Dal.Models.Breed", "Breed")
                        .WithMany("Individuals")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
